import Head from "next/head";
import { Paper, Typography } from "@mui/material";

import TaskList from "../components/TaskList/TaskList";

const index = () => {
  return (
    <>
      <Head>
        <title>Organizer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Paper>
          <Typography align="center" variant="h2">
            Task list
          </Typography>
          <TaskList />
        </Paper>
      </main>
    </>
  );
};

export default index;
